MODEL:
    NUM_CLASSES: 21
INPUT:
    IMAGE_SIZE: [300, 300]
DATASETS:
    TRAIN: ("voc_2007_trainval", "voc_2012_trainval")
    TEST: ("voc_2007_test", )
SOLVER:
    MAX_ITER: 5000
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 5e-4
  
OUTPUT_DIR: '/content/drive/MyDrive/colab/SSD/outputs/vgg_VOC'
EVAL_STEP: 1000
MODEL_SAVE_STEP: 1000
DATASET_DIR: ""